title: "Shuyue Chen"
description: "Website of Shuyue"

url: "https://YOURUSERNAME.github.io"
baseurl: ""

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "note"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
